pdf_viewer: &pdf_viewer 'pdfjs_viewer.html'

collections:
    '':
        index_paths: $liveweb
        wb_handler_class: !!python/name:via.rewriter.TemplateRewriteHandler
        templates:
            'application/pdf': *pdf_viewer
            'application/x-pdf': *pdf_viewer

        #frame_insert_html: ./templates/frame_insert.html
        #head_insert_html: ./templates/head_insert.html
        redir_to_exact: false

        cookie_scope: "root"

        rewrite_opts:
            rewrite_rel_canon: false
            client:
                no_rewrite_prefixes:
                    - "http://sense.tw/"
                    - "https://sense.tw/"
                    - "http://h.sense.tw/"
                    - "https://h.sense.tw/"
                    - "http://api.sense.tw/"
                    - "https://api.sense.tw/"
                    - "http://staging.sense.tw/"
                    - "https://staging.sense.tw/"
                    - 'http://localhost:5000/' # Hypothesis dev server
                    - 'http://localhost:3001/' # Hypothesis client dev server
                    - 'https://hypothes.is/'
                    - 'https://qa.hypothes.is/'
                    - 'https://cdn.hypothes.is/'
                    - '/assets/'

                no_rewrite_domain:
                    - "sense.tw"
                    - "doubleclick.net"
                    - "amp-error-reporting.appspot.com"
                    - "ampproject.org"
                    - "cdnjs.cloudflare.com"
                    - "gstatic.com"
                    - "googlesyndication.com"
                    - "gstatic.com"
                    - "google-analytics.com"
                    - "unpkg.com"
                    - "facebook.com"
                    - "bootstrapcdn.com"
                    - "youtube.com"
                    - "googletagmanager.com"
                    - "googletagservices.com"
                    - "google.com"
                    - "alexametrics.com"
                    - "scorecardresearch.com"
                    - "fbcdn.net"

                #skip_createElement: true

                http_cache: pass

                #skip_setAttribute: true
                #skip_dom: true
                #skip_postmessage: true

search_html: index.html
home_html: index.html

framed_replay: false
