pdf_viewer: &pdf_viewer 'pdfjs_viewer.html'

collections:
    '':
        index_paths: $liveweb
        wb_handler_class: !!python/name:via.rewriter.TemplateRewriteHandler
        templates:
            'application/pdf': *pdf_viewer
            'application/x-pdf': *pdf_viewer

        #frame_insert_html: ./templates/frame_insert.html
        #head_insert_html: ./templates/head_insert.html
        redir_to_exact: false

        cookie_scope: "root"

        rewrite_opts:
            rewrite_rel_canon: false
            client:
                no_rewrite_prefixes:
                    - "http://sense.tw/"
                    - "https://sense.tw/"
                    - "http://h.sense.tw/"
                    - "https://h.sense.tw/"
                    - "http://api.sense.tw/"
                    - "https://api.sense.tw/"
                    - "http://staging.sense.tw/"
                    - "https://staging.sense.tw/"
                    - 'http://localhost:5000/' # Hypothesis dev server
                    - 'http://localhost:3001/' # Hypothesis client dev server
                    - "https://googleads.g.doubleclick.net"
                    - "https://securepubads.g.doubleclick.net"
                    - "https://amp-error-reporting.appspot.com"
                    - "https://cdn.ampproject.org"
                    - "https://cdnjs.cloudflare.com"
                    - "https://fonts.gstatic.com"
                    - "https://ade.googlesyndication.com"
                    - "https://www.gstatic.com/"
                    - "https://www.google-analytics.com"
                    - "https://unpkg.com"
                    - "https://www.facebook.com"
                    - 'https://hypothes.is/'
                    - 'https://qa.hypothes.is/'
                    - 'https://cdn.hypothes.is/'
                    - '/assets/'

                #skip_createElement: true

                http_cache: pass

                #skip_setAttribute: true
                #skip_dom: true
                #skip_postmessage: true

search_html: index.html
home_html: index.html

framed_replay: false
