apiVersion: v1
kind: Service
metadata:
  name: viaserver-stage
  labels:
    run: viaserver-stage
spec:
  type: NodePort
  ports:
  - port: 9080
    targetPort: 9080
    nodePort: 30101
    protocol: TCP
    name: viaserver-stage-http
  selector:
    service: viaserver-stage
