steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/viaserver', '-t', 'asia.gcr.io/$PROJECT_ID/viaserver:$COMMIT_SHA', '-f', './Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "asia.gcr.io/$PROJECT_ID/viaserver"]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'replace'
  - '-f'
  - 'gcloud/nginx.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hypo'
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/viaserver'
  - 'viaserver=asia.gcr.io/$PROJECT_ID/viaserver:$COMMIT_SHA'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=asia-east1-c'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hypo'

